### ISSUE TITLE
RobotController.senseEnemyTowerLocations returns off-screen locations

### ISSUE THREAD

**Issue by zrneely** [battlecode/battlecode-server#15]
The javadoc says that it "Returns the locations of surviving enemy towers, unconstrained by sensor range or distance." When I call it, the 0th element returned is a MapLocation at (14115, 13473), which is greater than GameConstants.MAP_MAX_WIDTH and GameConstants.MAP_MAXA_HEIGHT, so there couldn't be a tower there.

This occurs on the lanes.xml map in version 1.0.0, and is untested on other maps or versions.

**Comment by battlecode-prod** [comment]
The maplocations are offset, so the corner is not 0,0. The maplocation
14115,13473 may actually be on the map.

Max

**Comment by zrneely** [comment]
I didn't realize that, thank you. Could this information be added to the MapLocation javadoc, or somewhere else that's appropriate?
