### ISSUE TITLE
The BroadcastSignal sent to the client should not contain the message itself

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-server#194]
because doing so will cause the messages to end up in the rms files. When that happens, other contestants will be able to view each others' messages, which might be a security hole / expose strategies.

Also, removing the message will save space.

**Comment by trun** [comment]
In theory contestants could already publish opponents messages as indicator strings to capture them, but :+1: for getting rid of them anyways.

**Comment by axc** [comment]
Closing due to not being necessary for this year anymore.
