### ISSUE TITLE
System.getProperty (bc.testing.something) doesn't work

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-server#199]
This is the feature to pass parameters from bc.conf into your bot (such as to specify what strategy to use, etc.).

http://battlecodeforum.org/t/bc-testing-doesnt-work/180/1

**Comment by axc** [comment]
Reopened; https://github.com/battlecode/battlecode-server/pull/202 was reverted because it seemed to cause a bug where using class loaders will freeze the engine.

System might need to interact with Config to get the "bc.testing" properties. (?)

**Comment by kazimuth** [comment]
Are you sure it was #202 causing that bug? It didn't touch classloaders at all.

**Comment by axc** [comment]
I'm really confused too, but after reverting that commit things seemed to work again.
