### ISSUE TITLE
java.lang.RuntimeException: visitDeathSignal of nonexistent robot

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-server#207]
Not sure how to replicate. This seems to happen in a scenario involving a robot dying due to viper infection damage.

Here's the forum post: http://battlecodeforum.org/t/java-lang-runtimeexception-visitdeathsignal-of-nonexistent-robot-3420/194/1

**Comment by nmccoy** [comment]
My initial guess is that this is happening when a viper attacks itself and dies in the middle of its own turn, meaning processEndOfTurn() and processBeingInfected() will run on a nonexistent robot.

**Comment by nmccoy** [comment]
I've managed to replicate the error by making vipers attack themselves when they are right about to die (and are infected). It should be a simple fix.
