### ISSUE TITLE
Issue with zombie spawn schedule

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-server#220]
There's a map that doesn't work properly:

http://battlecodeforum.org/t/possible-subtle-issue-in-server-zombie-spawn/216

**Comment by trun** [comment]
`Optional.ofNullable(parent)` instead of `Optional.of(parent)` at https://github.com/battlecode/battlecode-server/blob/master/src/main/battlecode/world/GameWorld.java#L834 ?

**Comment by axc** [comment]
That would fix the error. I'm hesitant to do that because it seems like we might have another bug if we are ever using a BuildSignal with a non-existent parent.
