### ISSUE TITLE
Update isTournamentLegal() for new map specs

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-server#225]
Specifically, check that all den locations are 30% closer to one team than the other

**Comment by bovard** [comment]
Question on this:

Does this mean?
```java
private boolean wellPlaced(MapLocation den, int distSquaredToA, int distSquaredToB) {
    if (distSquaredToA <= distSquaredToB) {
        return distSquaredToA < .7 * distSquaredToB;
    }
   if (distSquaredToB < distSquaredToA) {
      return distSquaredToB < .7 * distSquaredToB;
   }
}
```

**Comment by axc** [comment]
The latter.

"for a den D take the distance between D and the closest archon of team A: d_a and the distance between D and the closest archon of team B: d_b if d_a >= d_b, then d_a must be >= d_b*1.3 and vice versa." (from one of the other devs)

**Comment by kazimuth** [comment]
Also, those should just be distances, not distances squared :)

**Comment by bovard** [comment]
"Each zombie den will be at least 30% closer (in terms of radiusSquared) to one team’s closest archon than to the other team’s closest archon."

**Comment by bovard** [comment]
I definitely think that radius makes more sense. 8^2 / 7^2 = 1.30

**Comment by bovard** [comment]
Thanks! I'll update [zden](https://github.com/bovard/zden/blob/master/lib/map.js#L15) to use radius and the 1.3

**Comment by uldivad9** [comment]
It was actually intended to be a comparison of radiusSquared.
