### ISSUE TITLE
Add indicator strings / bytecode counts in client

### ISSUE THREAD

**Issue by nmccoy** [battlecode/battlecode-server#328]
People in IRC seem to miss them. This would involve client/schema/server changes.

**Comment by jbloxham** [comment]
I'd thought the logs we were adding were going to offer more functionallity? @ygina

**Comment by ygina** [comment]
The logs are there now, let me know if you want them to be different in any way.

I can bring back the bytecode counts, but that will require schema changes. I assume everything will auto-update and be fine?

**Comment by ygina** [comment]
I could do something like clicking the robot shows the last thing printed out; not sure the best way to go about doing this.
