### ISSUE TITLE
degreesBetween() returns negative value

### ISSUE THREAD

**Issue by ChesleyTan** [battlecode/battlecode-server#329]
`radiansBetween()` and `degreesBetween()` don't seem to return a bounded positive value, as stated in the API specifications. From looking at the implementation, it seems modulo of a negative number is not properly handled.

**Comment by nmccoy** [comment]
I feel like the best change here is to make the the code mathematically sound (change modulo to something else to guarantee preserving sign), and change the spec to return a number in (-180,180]. This gives more information, and competitors can just take Math.abs() if they want. Thoughts?

**Comment by ChesleyTan** [comment]
Sounds good to me.
