### ISSUE TITLE
setIndicatorDot() off-by-one bug

### ISSUE THREAD

**Issue by ChesleyTan** [battlecode/battlecode-server#343]
It appears that there's an off-by-one/initialization issue in the implementation of `setIndicatorDot()`. The first call to `setIndicatorDot()` always draws a dark-green dot, while subsequent calls draw the correct color, but off-by-one (i.e., if my first call specified a dark-gray, and my second call specified a white, then the second dot drawn would be dark gray, and the third dot drawn would be white).

**Comment by ygina** [comment]
https://github.com/battlecode/battlecode-client-17/pull/137
