### ISSUE TITLE
Logs should contain exceptions/errors

### ISSUE THREAD

**Issue by ygina** [battlecode/battlecode-server#360]
Right now, logs only have System.out.println() output. It would be helpful to users to also display errors and uncaught exceptions. Normal logs have a header of the form "[A:GARDENER#11329@2]". In the error header, I would want at least the round number, and if possible the team. something like "[A:ERROR@2]" or "[A:ERROR#11329@2]".

**Comment by Pear0** [comment]
You can somewhat mitigate this by wrapping all code in your `run()` method in a try statement.

I have this in my robot code:
```java
public static void run(RobotController rc) throws GameActionException {
    try {
        ...
    } catch(Throwable e) {
        e.printStackTrace();
    }
}
```

**Comment by ygina** [comment]
Closing since we have improved error logging now.
