### ISSUE TITLE
rotateLeftDegrees() and rotateRightDegrees()

### ISSUE THREAD

**Issue by ygina** [battlecode/battlecode-server#361]
See: http://www.battlecodeforum.org/t/rotateleftdegrees-and-rotaterightdegrees-reversed/343
Does this have to do with the north/south issue?

**Comment by nmccoy** [comment]
Can we change North/South to their original values, then just change the client to make the y axis go up? Angles are going to become a lot less intuitive if we change the way rotation works.

**Comment by ygina** [comment]
Yup, can do.
