### ISSUE TITLE
Game not starting and ending correctly

### ISSUE THREAD

**Issue by dwang733** [battlecode/battlecode-server#372]
For some reason, when viewing matches from the client, it sometimes doesn't seem to show the very last round. This is apparent when the opponent has 10,000 victory points, but it doesn't show the round where they donate them, as seen here.
![image](https://cloud.githubusercontent.com/assets/21963247/21874722/c9cbed0e-d844-11e6-9053-d836272e0622.png)

Another bug I found is that the game doesn't seem to start on round 0. For example, this following code for an archon doesn't spawn a gardener as expected
```java
if (rc.getRoundNum() == 0) {
    rc.hireGardener(randomDirection());
    Clock.yield();
}
```
However, if I change the 0 to a 2, the gardener is created.

**Comment by nmccoy** [comment]
I created https://github.com/battlecode/battlecode-client-17/issues/147 for the last round issue.

For the other bug, there isn't a round 0. It always starts at 1 :)
