### ISSUE TITLE
Robots do not always get a turn on the round they were spawned

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-server#374]
The specs say: "This also means that if a robot builds another robot during a round, the new robot will get a turn later in that round" and also "Gardener immediately appears centered at this location with full health, and begins running player code the following turn"

* On the map shrine, a gardener hired on round 1 will not make an action until round 2.
* However, on the map Enclosure, a gardener hired on round 1 might actually move before some of the archons on the map.

Related: http://battlecodeforum.org/t/execution-order-in-first-round-broken/390

**Comment by axc** [comment]
It appears that in general, turn order has nothing to do with spawn order.

```[B:GARDENER#11621@2999] I was born 215
[B:LUMBERJACK#13188@2999] I was born 2236
[B:GARDENER#13581@2999] I was born 146
[B:LUMBERJACK#11409@2999] I was born 2997
[B:GARDENER#12785@2999] I was born 1664
[B:GARDENER#10813@2999] I was born 2838
[B:GARDENER#10613@2999] I was born 2286
[B:GARDENER#10999@2999] I was born 906
[B:GARDENER#11188@2999] I was born 2907
[B:SOLDIER#10394@2999] I was born 2512
[B:GARDENER#12155@2999] I was born 1320
[B:GARDENER#13527@2999] I was born 2
[B:GARDENER#13920@2999] I was born 2561
[B:GARDENER#10767@2999] I was born 2147
[B:GARDENER#13327@2999] I was born 2423
[B:GARDENER#13714@2999] I was born 561
[B:GARDENER#12727@2999] I was born 2631
[B:GARDENER#12922@2999] I was born 630
[B:GARDENER#11539@2999] I was born 423
[B:GARDENER#13794@2999] I was born 1595
[B:GARDENER#11915@2999] I was born 1113
[B:GARDENER#10137@2999] I was born 2
[B:GARDENER#10525@2999] I was born 1388
[B:GARDENER#10570@2999] I was born 491```

**Comment by DollarAkshay** [comment]
These are the changes that I think would be helpful :

**Execution Order by Type :**  
`Archon > Gardener > Lumberjack > Scout > Soldier > Tank`

** Execution Order within a Type :**
`Lowest ID > Highest ID`

New units should only be able to tank an action the next turn.

**Comment by nmccoy** [comment]
Currently execution order is governed by ObjectInfo.eachRobot:
```
public void eachRobot(TObjectProcedure<InternalRobot> op) {
        gameRobotsByID.forEachValue(op);
    }
```
forEachValue() goes in order based on the hash of the Robot's ID, which is effectively random but means order will be consistent each turn.

We could add this to the spec, but I think that's kinda messy. I'll add another structure to ensure they are run in spawn order.

**Comment by DollarAkshay** [comment]
@nmccoy Well it dosent actually execute in the same order. I just noticed that it changes when ever a new unit is produced. 

I have this logic where the first scout that executes becomes the explorer. Rest all attack.

So I had just 1 scout and it was exploring. My gardener made another one and suddenly the new Scout became the explorer and the old one the attacker.
