### ISSUE TITLE
[undocumented] senseNearbyRobots returns robots in sorted order, at least most of the time

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-server#379]
1) senseNearbyRobots (and similar methods) uses the SpatialIndex nearestNUnsorted method, which specifically doesn't attempt to sort the returned robots. However, in practice, the robots tend to end up sorted in decreasing distance order, perhaps due to the underlying data structure. I haven't tested enough to say whether this always happens or not.

2) Teams that realize this can take advantage of it, and teams that don't will end up using up bytecodes to sort the list. It's common to want to find the nearest robot. This can be unfair to the teams that don't dive into the source code of our engine.

3) Some ideas:
    * document this sorting (and also use nearestNSorted, to guarantee that the distances are sorted)
    * return robots in a randomly shuffled order
    * return the robots in some other sorted order, like ID

**Comment by kazimuth** [comment]
I'm in favor of just sorting it.
