### ISSUE TITLE
Robots can have ID 0

### ISSUE THREAD

**Issue by xytosis** [battlecode/battlecode-server#416]
it is now possible for robots to have id 0, which is game breaking and doesn't follow the specs.

**Comment by nmccoy** [comment]
Could you please elaborate? I'm not quite sure what you mean the the "it is now possible" part, as I don't think anything has recently changed regarding ID generation.

**Comment by nmccoy** [comment]
Problem was found in Shrine. This map will have to be remade using the map generator.

**Comment by jbloxham** [comment]
Resolved by #422 .
