### ISSUE TITLE
Possibly change bullet execution order

### ISSUE THREAD

**Issue by nmccoy** [battlecode/battlecode-server#431]
http://www.battlecodeforum.org/t/something-fishy-about-extreme-dodging/608/2

The issue is about the old execution order but even with the new one point-blank combat is unintuitive. Example: Two robots are touching. One robot shoots at the other. The bullet overlaps with the robot's body, but it can still move away from the bullet before it propagates. This seems unintuitive to me, so we might want to put a bullet's execution order directly after the robot that fires it.

**Comment by jbloxham** [comment]
Perhaps we could make it such that robots check whether they occupy the same space as a bullet at the start of a turn?

**Comment by nmccoy** [comment]
I think I might make it such that if a bullet is spawned on top of a robot/tree, it will immediately deal damage during the turn of the robot that fired it.

**Comment by jbloxham** [comment]
Sure. My main problem with having bullets propagate immediately after the robot that fires them is that this would be surprisingly difficult to implement.
